### ISSUE TITLE
Final tree file

### ISSUE THREAD

**Issue by pavlo888** [davised/automlsa2#2]
Hi @davised, 

I am currently conducting an MLSA in a large collection of bacterial genomes (~200). I successfully managed to run your amazing pipeline and then I obtained my final tree. 

Is the .nex.treefile the the final tree? 

Cheers, 
Pablo

**Comment by davised** [comment]
That's correct.

There should be a line in your log file that explains what the final output tree is, and it does end in .nex.treefile.
